sonar.projectKey=CarlosRomero123_EBOGE
sonar.organization=carlosromero123
sonar.host.url=https://sonarcloud.io

# Analiza todo el código fuente
sonar.sources=EBOGE/src

# Aquí vamos a poner los .class (solo del modelo)
sonar.java.binaries=build

sonar.sourceEncoding=UTF-8
