sonar.projectKey=CarlosRomero123_EBOGE
sonar.organization=carlosromero123
sonar.host.url=https://sonarcloud.io

# Ruta donde están los .java, relativa a la raíz del repo
sonar.sources=EBOGE/src

# Carpeta donde vamos a poner los .class compilados
sonar.java.binaries=build

sonar.sourceEncoding=UTF-8
